<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv='Content-Type' content='text / html; charset = UTF-8' />

<style>

body {
    background-color: #f1f1f1;
    font-family: "Lato", sans-serif;
}

.sidenav {
    height: 100%;
    width: 200px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #4682B4;
    overflow-x: hidden;
    padding-top: 20px;
}

.sidenav a {
    padding: 6px 8px 6px 16px;
    text-decoration: none;
    font-size: 25px;
    color: #DCDCDC;
    display: block;
}

.sidenav a:hover {
    color: #696969;
}

.main {
    margin-left: 200px; /* Same as the width of the sidenav */
    font-size: 28px; /* Increased text to enable scrolling */
    padding: 0px 10px;
}

@media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
}

.row {
    margin: 8px -16px;
}

/* Add padding BETWEEN each column */
.row,
.row > .column {
    padding: 10px;
}

/* Create four equal columns that floats next to each other */
.column {
    float: left;
    width: 30%;
}

/* Clear floats after rows */
.row:after {
    content: "";
    display: table;
    clear: both;
}

/* Content */
.content {
    background-color: #f1f1f1;
    padding: 10px;
}
<!--Кнопка-->
tr:nth-child(even){background-color: #f2f2f2}

input[type=submit] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: #45a049;
}
</style>

</head>
<body>

<div class="sidenav">
    <form action="exit.php">
    <input type="submit" value="Выйти" >
    </form>
  <a href="lk.phtml">Личный кабинет</a>
  <a href="medcard.phtml">Медицинские карты</a>
  <a href="doctors.phtml">Врачи</a>
  <a href="pricelist.phtml">Прайс</a>
  <a href="medicines.phtml">Медикаменты</a>
</div>

<div class="main">
<h2>Наши специалисты</h2>

<?php
session_start();
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

if ($_SESSION['isAdmin'] == 1)
{
    echo "<form action='doctorsenter.html'>
    <input type='submit' value='Добавить' >
    </form>";
    echo "<form action='doctorsdelete.html'>
    <input type='submit' value='Удалить' >
    </form>";
}

//подключение к БД
$host="localhost";
$port=3360;
$socket="";
$user="root";
$password="";
$dbname="vetclinic";

$con = new mysqli($host, $user, $password, $dbname, $port, $socket)
    or die ('Could not connect to the database server' . mysqli_connect_error());

//запрос на получение данных из БД
$show = $con->query("SELECT * FROM doctors WHERE iddoctors>0");

$lastid = $show->num_rows;
echo "<div class='row'>";
$all = $show->fetch_all(MYSQLI_ASSOC);
foreach($all as $row)
{
    echo "<div class='column'>
          <div class='content'>";
      echo "<h2>". $row["Name"] . "</h2>";
      echo "<p class='title'>". $row["Specialization"] . "</p>";
      echo "<p>" . $row["Degree"] . "</p>";
      echo "<p>" . $row["TelNum"] . "</p>";
      echo "<p>" . $row["Email"] . "</p>";
    echo "</div></div>";
}
?>
</div>
</body>
</html> 