<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv='Content-Type' content='text / html; charset = UTF-8' />
<link rel="stylesheet" type="text/css" href="style.css">
</head>
<style>
body {font-family: Arial, Helvetica, sans-serif;}

input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-top: 6px;
    margin-bottom: 16px;
    resize: vertical;
}

input[type=submit] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: #45a049;
}

.container {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
}
</style>
<body>

<div class="sidenav">
    <form action="exit.php">
    <input type="submit" value="Выйти" >
    </form>
  <a href="lk.phtml">Личный кабинет</a>
  <a href="medcard.phtml">Медицинские карты</a>
  <a href="doctors.phtml">Врачи</a>
  <a href="pricelist.phtml">Прайс</a>
  <a href="medicines.phtml">Медикаменты</a>
</div>

<div class="main">
  <h2>Прайс</h2>
<form action="pricelist.html">
    <input type="submit" value="Добавить" >
</form>
<?php
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
//подключение к БД
$host="localhost";
$port=3360;
$socket="";
$user="root";
$password="";
$dbname="vetclinic";

$con = new mysqli($host, $user, $password, $dbname, $port, $socket)
    or die ('Could not connect to the database server' . mysqli_connect_error());

//запрос на получение данных из БД
$show = $con->query("SELECT * FROM services");

$lastid = $show->num_rows;
echo "<div class='row'>";
$all = $show->fetch_all(MYSQLI_ASSOC);
foreach($all as $row)
{
    echo "<div class='column'>
          <div class='content'>";
      echo "<h3>". $row["Name"] . "</h3>";
      echo "<h4>". $row["Cost"] . "</h4>";
      echo "<p>" . $row["Description"] . "</p>";
    echo "</div></div>";
}
?>
</div>
     
</body>
</html> 
